server:
  port: 7000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由

      routes:
        - id: xinblog-admin                       #路由的ID，没有固定规则但要求唯一，建议配合服务名
          # uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://xinblog-admin        #匹配后提供服务的路由地址
          predicates:
          - Path=/renren-fast/**         # 断言，路径相匹配的进行路由
    nacos:
      discovery:
        server-addr: 47.98.130.159:8848

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 3000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 3000
  #一旦超时，显示错误页
